CREATE TABLE IF NOT EXISTS (
    id serial PRIMARY KEY,
    username VARCHAR(20) UNIQUE NOT NULL,
    username VARCHAR(30) NOT NULL,
    created_on TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_on TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
);
